conky.config = {
    alignment = 'bottom_left',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    double_buffer = true,
    font = 'DejaVu Sans Mono:size=10',
    gap_x = 25,
    gap_y = 50,
    minimum_width = 200,
    no_buffers = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override', -- Crucial for i3 to keep it on the background
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    update_interval = 1.0,
    use_xft = true,
}

conky.text = [[
${color grey}SYSTEM ${hr 2}
${color white}Uptime:$color $uptime
${color white}CPU Usage:$color $cpu% ${cpubar 4}
${color white}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color white}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}

${color grey}STORAGE ${hr 2}
${color white}/ $at_path{/}${fs_used /}/${fs_size /} ${fs_bar 6 /}

${color grey}BATTERY ${hr 2}
${color white}Status:$color ${battery_percent}% ${battery_bar 6}
${color white}Time left:$color $battery_time

${if_match "Playing" == "${exec playerctl status 2>/dev/null}"}
${color grey}MEDIA ${hr 2}
${exec playerctl metadata --format '{{ artist }} - {{ title }}'}
${execbar playerctl metadata --format "{{ position / mpris:length * 100 }}"}
${execi 1 playerctl -p spotify metadata --format "{{ duration(position) }} / {{ duration(mpris:length) }}"}
${endif}

]]
